config/routes.rb
Rails.application.routes.draw do
  resources :ai_models
  devise_for :users

  root to: 'index#index'

  get 'people/', to: 'index#people'

  post 'users/tokens/generate_post/', to: 'authentication_tokens#generate'
  get  'users/tokens/generate/', to: 'authentication_tokens#generate_get', as: :generate_token
  get 'users/:id/models', to: 'ai_models#user_models', as: :user_models

  get '/discord', to: 'index#discord'

  post '/ai_models/create_auto', to: 'ai_models#create_auto'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
end

app/models/ai_model.rb
class AiModel < ApplicationRecord
  belongs_to :user
  has_one_attached :file

  validates :score, 
    comparison: { less_than_or_equal_to: 1, message: "must be between 0 and 1 (inclusive)" },
    comparison: { greater_than_or_equal_to: 0, message: "must be between 0 and 1 (inclusive)" }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/authentication_token.rb
class AuthenticationToken < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :ai_model
  has_many :authentication_token, dependent: :destroy

  validates :email, format: { with: /\A\d+@fjuhsd\.org\z/, message: "must be an school email."}
end

app/controllers/ai_models_controller.rb
class AiModelsController < ApplicationController
  protect_from_forgery except: :create_auto

  before_action :set_ai_model, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: :create_auto

  # GET /ai_models or /ai_models.json
  def index
    @ai_models = AiModel.all
    return render 'index', locals: { title: 'Model Library' }
  end

  # GET /ai_models/new
  def new
    @ai_model = AiModel.new
  end

  # GET /ai_models/1/edit
  def edit
  end

  def create_auto
    data = JSON.parse params[:json].read
    data['ai_model']['file'] = params[:upload_file]

    token = AuthenticationToken.find_by(token: data['token'])
    if token.nil?
      return render plain: "ERR_TOKEN_NOT_FOUND"
    end
    data['ai_model']['user_id'] = token.user_id

    ai_model = AiModel.new data['ai_model']

    previous_model = AiModel.find_by name: ai_model.name, user: token.user_id

    unless previous_model.nil?
      previous_model.delete
    end
    
    if ai_model.save
      return render plain: "OK"
    else
      return render plain: "ERR_SAVE"
    end
  end

  def user_models
    user = User.find(params[:id])
    @ai_models = AiModel.where(user: user)
    return render 'index', locals: { title: "Models for #{user.email}" }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ai_model
      @ai_model = AiModel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ai_model_params
      params.require(:ai_model).permit(:file, :user_id, :description, :name, :score)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authentication_tokens_controller.rb
class AuthenticationTokensController < ApplicationController
  before_action :authenticate_user!

  def generate
    @token = current_user.authentication_token.new(token: helpers.new_token_string())
    @token.save!

    render 'generate_post'
  end

  def generate_get
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  before_action :authenticate_user!, only: :discord

  def index
  end

  def people
  end

  def discord
    redirect_to "https://discord.gg/gSDs5kYxeb", allow_other_host: true
  end
end

app/helpers/ai_models_helper.rb
module AiModelsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_token_helper.rb
module AuthTokenHelper
    def new_token_string
        token_string = ""
        characters = [*('a'..'z'), *('A'..'Z'), *('0'..'9')]
        length = 16
    
        length.times do
          token_string << characters.sample
        end

        token_string
    end
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/ai_models/_ai_model.html.erb
<div id="<%= dom_id ai_model %>", class="container p-2 m-4 rounded border bg-light">
  <div class="row">
    <div class="col m-2">
      <p>
        <%= ai_model.description %>
      </p>
    </div>
    <div class="vr border p-1"></div>
    <div class="col m-2 position-relative">
      <p>
        <%= link_to 'Download this model for unpickling', ai_model.file if ai_model.file.attached? %>
      </p>
      <p>
        <strong>Owner:</strong> <%= ai_model.user.email %>
      </p>
      <p>
        <strong>Name:</strong> <%= ai_model.name %>
      </p>
      <div class="d-flex justify-content-between">
        <p>
          <strong>Score:</strong> <%= ai_model.score %>
        </p>
        <p class="d-flex justify-content-end">
          <button class="btn btn-primary copy-button" data-copy-button="<%= rails_blob_url ai_model.file %>">Copy Link</button>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/ai_models/_form.html.erb
<%= form_with(model: ai_model) do |form| %>
  <% if ai_model.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(ai_model.errors.count, "error") %> prohibited this ai_model from being saved:</h2>

      <ul>
        <% ai_model.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :file, style: "display: block" %>
    <%= form.file_field :file %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :score, style: "display: block" %>
    <%= form.text_field :score %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/ai_models/edit.html.erb
<h1>Editing ai model</h1>

<%= render "form", ai_model: @ai_model %>

<br>

<div>
  <%= link_to "Show this ai model", @ai_model %> |
  <%= link_to "Back to ai models", ai_models_path %>
</div>

app/views/ai_models/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="text-center mb-3 mt-3">
  <%= title %>
</h1>

<div id="ai_models">
  <% @ai_models.each do |ai_model| %>
    <%= render ai_model %>
  <% end %>
</div>

<%= javascript_include_tag 'copybutton' %>

app/views/ai_models/new.html.erb
<h1>New ai model</h1>

<%= render "form", ai_model: @ai_model %>

<br>

<div>
  <%= link_to "Back to ai models", ai_models_path %>
</div>

app/views/authentication_tokens/_token_show.html.erb
<div class="container bg-light rounded">
    <% p '_authentication_token page' %>
    <% p authentication_token %>

    <h3>Token: <%= authentication_token.token %></h3>
</div>

app/views/authentication_tokens/generate_get.html.erb
<div class='ms-a me-a container rounded bg-light p-3 mt-5 border'>
    <h2>Generate an authentication token</h2>
    <p>You must generate an authentication token to be able to automatically access the model storage API</p>
    
    <%= form_with(url: '/users/tokens/generate_post/',  method: :post, local: true, data: { turbo: false }) do |form| %>
        <% form.submit 'Generate' %>
    <% end %>
</div>

app/views/authentication_tokens/generate_post.html.erb
<h1>New auth token generated successfully.</h1>

<% p "IN GENERATE.HTML.ERB" %>

<%= render 'token_show', authentication_token: @token %>

app/views/index/index.html.erb
<section id='image-section' class='image-section overflow-hidden'>
    <h1 class="text-white slide-in-from-left" id='image-text'>
        <%= link_to 'Join', new_user_registration_path, class: 'underline' %> Troy AI Club.
    </h1>
    <h1 class="text-white slide-in-from-right ms-a me-a p-a" id='image-text-2'></h1>
</section>
<section id='about' class='p-4 pt-5 pb-5'>
    <p id='club-description' class='h1 m-4 position-relative'></p>
</section>
<section id='links' class='bg-dark overflow-hidden'>
    <div class="container mt-4 mb-4">
        <div class="row">
            <div class="col-sm-4">
                <div class="card text-center p-5 link-card">
                    <div class='image-card-area d-flex align-items-center'>
                        <a href="/discord" target='_blank'>
                            <img class="card-img-top max-w-100" src="/assets/discordlogo.png" alt="Discord Logo">
                        </a>
                    </div>
                    <hr class='ms-0 me-0 mt-4 mb-4 bg-dark border-4 border-info'>
                    <div class="card-body">
                        <p class="card-text">
                            Click <a href="/discord" target='_blank'>here</a> to join our Discord server, where we talk about all things AI Club and a significant amount of things not AI Club.
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="card text-center p-5 link-card">
                    <div class='image-card-area d-flex align-items-center'>
                        <img class="card-img-top max-w-100" src="/assets/aiclublogo.webp" alt="Troy AI Club Logo">
                    </div>
                    <hr class='ms-0 me-0 mt-4 mb-4 bg-dark border-4 border-info'>
                    <div class="card-body">
                        <p class="card-text">Club meetings are afterschool basically every day in the library - stop by at any time and you'll be able to hear Avni from across the room.</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="card text-center p-5 link-card">
                    <div class='image-card-area d-flex align-items-center'>
                        <a href="https://www.kaggle.com/rxshark" target='_blank'>
                            <img class="card-img-top max-w-100" src="/assets/kagglelogo.png" alt="Kaggle.com Logo">
                        </a>
                    </div>
                    <hr class='ms-0 me-0 mt-4 mb-4 bg-dark border-4 border-info'>
                    <div class="card-body">
                        <p class="card-text">
                            We use Kaggle for coding because it's unblocked and free. 
                            There's <a href="https://www.kaggle.com/rxshark" target='_blank'>the club president</a>,
                            <a href="https://www.kaggle.com/siiverfish" target='_blank'>me the website dude</a>, 
                            and <a href="https://www.kaggle.com/Avssss" target='_blank'>Avni </a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<%= javascript_include_tag 'typinganimation' %>
<%= javascript_include_tag 'avnishackertype' %>

app/views/index/people.html.erb
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<%= javascript_include_tag 'people-gallery.js' %>

<section id="profile-cards">
    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <div id="First slide" style="display: flex; justify-content: space-evenly;">
                    <div class="card" style="width: 18em; margin: 2em;">
                        <img class="card-img-top" src="/assets/defaultprofile.jpeg" alt="person-1">
                        <div class="card-body">
                            <h5 class="card-title" style="text-align: center;">Some Fool</h5>
                            <p class="card-text" style="text-align: center;">These are comically average human beings, 
                                sometimes they have more than one brain cell. 
                                Please do not assume they can help you. 
                                We made fancy titles so they can get into any college that is willing accept.</p>
                            <div class="contact">
                                <a href="#" class="btn btn-primary" style="text-align: center; ">Kaggle</a>
                                <a href="#" class="btn btn-primary" style="text-align: center;">Discord</a>
                            </div>
                        </div>
                    </div>

                    <div class="card" style="width: 18em; margin: 2em;">
                        <img class="card-img-top" src="/assets/defaultprofile.jpeg" alt="person-2">
                        <div class="card-body">
                            <h5 class="card-title" style="text-align: center;">Some Fool</h5>
                            <p class="card-text" style="text-align: center;">These are comically average human beings, 
                                sometimes they have more than one brain cell. 
                                Please do not assume they can help you. 
                                We made fancy titles so they can get into any college that is willing accept.</p>
                            <div class="contact">
                                <a href="#" class="btn btn-primary" style="text-align: center; ">Kaggle</a>
                                <a href="#" class="btn btn-primary" style="text-align: center;">Discord</a>
                            </div>
                        </div>
                    </div>

                    <div class="card" style="width: 18em; margin: 2em;">
                        <img class="card-img-top" src="/assets/defaultprofile.jpeg" alt="person-3">
                        <div class="card-body">
                            <h5 class="card-title" style="text-align: center;">Some Fool</h5>
                            <p class="card-text" style="text-align: center;">These are comically average human beings, 
                                sometimes they have more than one brain cell. 
                                Please do not assume they can help you. 
                                We made fancy titles so they can get into any college that is willing accept.</p>
                            <div class="contact">
                                <a href="#" class="btn btn-primary" style="text-align: center; ">Kaggle</a>
                                <a href="#" class="btn btn-primary" style="text-align: center;">Discord</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="carousel-item">
                <div id="Second slide" style="display: flex; justify-content: space-evenly;">
                        <div class="card" style="width: 18em; margin: 2em;">
                            <img class="card-img-top" src="/assets/defaultprofile.jpeg" alt="person-4">
                            <div class="card-body">
                                <h5 class="card-title" style="text-align: center;">Some Fool Pt.2</h5>
                                <p class="card-text" style="text-align: center;">111These are comically average human beings, 
                                    sometimes they have more than one brain cell. 
                                    Please do not assume they can help you. 
                                    We made fancy titles so they can get into any college that is willing accept.</p>
                                <div class="contact">
                                    <a href="#" class="btn btn-primary" style="text-align: center; ">Kaggle</a>
                                    <a href="#" class="btn btn-primary" style="text-align: center;">Discord</a>
                                </div>
                            </div>
                        </div>
                        
                        <div class="card" style="width: 18em; margin: 2em;">
                            <img class="card-img-top" src="/assets/defaultprofile.jpeg" alt="person-5">
                            <div class="card-body">
                                <h5 class="card-title" style="text-align: center;">Some Fool Pt. 2</h5>
                                <p class="card-text" style="text-align: center;">These are comically average human beings, 
                                    sometimes they have more than one brain cell. 
                                    Please do not assume they can help you. 
                                    We made fancy titles so they can get into any college that is willing accept.</p>
                                <div class="contact">
                                    <a href="#" class="btn btn-primary" style="text-align: center; ">Kaggle</a>
                                    <a href="#" class="btn btn-primary" style="text-align: center;">Discord</a>
                                </div>
                            </div>
                        </div>

                        <div class="card" style="width: 18em; margin: 2em;">
                            <img class="card-img-top" src="/assets/defaultprofile.jpeg" alt="person-6">
                            <div class="card-body">
                                <h5 class="card-title" style="text-align: center;">Some Fool Pt. 2</h5>
                                <p class="card-text" style="text-align: center;">These are comically average human beings, 
                                    sometimes they have more than one brain cell. 
                                    Please do not assume they can help you. 
                                    We made fancy titles so they can get into any college that is willing accept.</p>
                                <div class="contact">
                                    <a href="#" class="btn btn-primary" style="text-align: center; ">Kaggle</a>
                                    <a href="#" class="btn btn-primary" style="text-align: center;">Discord</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span id="my-arrow" class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only"></span>
        </a>
        
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span id="my-arrow2" class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only"></span>
        </a>
    </div>
</section>

app/views/layouts/_flash_messages.html.erb
<% position_modifier = 50 %>
<% if notice %>
    <p class="notice alert alert-success alert-dismissible position-fixed m-3 z-front">
        <%= notice %>
        <button type="button" data-bs-dismiss="alert" aria-label="Close" class='close btn btn-transparent'>
            <span aria-hidden="true">&times;</span>
        </button>
    </p>
<% end %>
<% if alert %>
    <p class="alert alert-warning alert-dismissible position-fixed m-3 z-front">
        <%= alert %>
        <button type="button" data-bs-dismiss="alert" aria-label="Close" class='close btn btn-transparent'>
            <span aria-hidden="true">&times;</span>
        </button>
    </p>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar position-fixed top-0 w-100 navbar-expand-lg blue-gradient ps-2 p-0 z-10">
  <a class="navbar-brand" href="#" id='navbar-title'><b>Troy AI</b></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ms-auto">
      <li class="nav-item active">
        <%= link_to 'Home', root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/#about">About</a>
      </li>
      <li class="nav-item">
        <%= link_to 'People', people_path, class: 'nav-link' %>
      </li>
      <% if not user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Log In', new_user_session_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Join', new_user_registration_path, class: 'nav-link' %>
        </li>
      <% end %>

      <% if user_signed_in? %>
        <div class="vr ms-2 me-2"></div>
        <li class="nav-item dropdown me-2 ms-2">
          <a class="nav-link dropdown-toggle z-10" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= current_user.email %>
          </a>
          <ul class="dropdown-menu dropdown-menu-end z-10" aria-labelledby="navbarDropdown">
            <li><%= link_to 'Generate API Token', generate_token_path, class: 'dropdown-item' %></li>
            <li><%= link_to 'My Models', user_models_path(current_user), class: 'dropdown-item' %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to 'Sign out', destroy_user_session_path, class: 'text-danger dropdown-item', data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to sign out?' } %></li>
          </ul>
        </li>
      <% end %>
    </ul>
  </div>
</nav>
<div class='p-3'>.</div>

app/views/layouts/application.html.erb
<!-- 
  Welcome to the code. This website is made with Ruby on Rails version 7.0.4.3 by me, Ivan.
  All the stuff is (mostly) handwritten HTML and CSS.
-->

<!DOCTYPE html>
<html>
  <head>
    <title>Troy AI</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

    <%= favicon_link_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render partial: 'layouts/navbar' %>
    <%= render partial: 'layouts/flash_messages' %>

    <%= yield %>
  </body>
</html>